[project]
name = "dspy-intro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dspy>=3.0.1",
    "polars>=1.32.3",
    "python-dotenv>=1.1.1",
]
